name: Daily Pokemon Price Pipeline

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pandas
          pip install requests
          pip install psycopg2-binary
          pip install python-dotenv
          pip install google-api-python-client
          pip install google-auth

      - name: Run Pokemon Price Pipeline
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PRICECHARTING_URL: ${{ secrets.PRICECHARTING_URL }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python pokemon_prices.py