name: Daily Card Shows Scraper

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 14 * * *' # adjust time as desired

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r scripts/python/requirements.txt

      - name: Run Card Shows Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/python/card_shows_scraper.py